---
- hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install DHCP server
      apt:
        name: isc-dhcp-server
        state: present

    - name: Configure DHCP server
      template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
      notify: Restart DHCP service

  handlers:
    - name: Restart DHCP service
      service:
        name: isc-dhcp-server
        state: restarted

#subnet 192.168.1.0 netmask 255.255.255.0 {
#  range 192.168.1.10 192.168.1.50;
#  option subnet-mask 255.255.255.0;
#  option domain-name "example.com";
#  option domain-name-servers 8.8.8.8, 8.8.4.4;
#  option routers 192.168.1.1;
#  default-lease-time 600;
#  max-lease-time 7200;
#}