---
- name: Install and configure MySQL
  hosts: mysql-node
  become: true
  vars:
    mysql_root_password: "risso"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Secure MySQL installation
      expect:
        command: mysql_secure_installation
        responses:
          'Enter password for user "root":': "{{ mysql_root_password }}"
          'Press y|Y for Yes, any other key for No:': "y"
          'New password:': "{{ mysql_root_password }}"
          'Re-enter new password:': "{{ mysql_root_password }}"
          'Change the password for root ? ((Press y|Y for Yes, any other key for No) :': "n"
          'Remove anonymous users? (Press y|Y for Yes, any other key for No) :': "y"
          'Disallow root login remotely? (Press y|Y for Yes, any other key for No) :': "y"
          'Remove test database and access to it? (Press y|Y for Yes, any other key for No) :': "y"
          'Reload privilege tables now? (Press y|Y for Yes, any other key for No) :': "y"

    - name: Restart MySQL service
      service:
        name: mysql
        state: restarted
