---
- hosts: localhost
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Set root password for MySQL
      debconf:
        name: 'mysql-server'
        question: 'mysql-server/root_password'
        vtype: 'password'
        value: 'myStrongPassword'
        state: 'present'

    - name: Confirm root password for MySQL
      debconf:
        name: 'mysql-server'
        question: 'mysql-server/root_password_again'
        vtype: 'password'
        value: 'myStrongPassword'
        state: 'present'

    - name: Ensure MySQL service is running and enabled
      service:
        name: mysql
        state: started
        enabled: yes